### PR TITLE
Update readme.txt

### PR DESCRIPTION
**Pull request by frranck**

### CODE REVIEW

**Comment by gingerbeardman** [comment]
what is the reason for this change? @frranck

**Comment by frranck** [comment]
Isn't the "-=== PrBoom core for RetroArch ===" section a copy/paste typo ?
this is the file about **Mr**Boom

**Comment by gingerbeardman** [comment]
Good spot, but I think your edit is a little heavy? You can just replace every instance of `PrBoom` with `MrBoom` and the readme would be valid.

**Comment by frranck** [comment]
@gingerbeardman No I think it's correct, it was twice in the file once with mrboom, once with prBoom

**Comment by frranck** [comment]
https://github.com/KMFDManic/NESC-SNESC-Modifications/tree/master/_km_mrboom_11_9_17.hmod

**Comment by gingerbeardman** [comment]
Oh, I see! Sorry about that, ignore me 😂

**Comment by KMFDManic** [comment]
Thank you, @frranck !  I will update tomorrow am:)  Friggin love the Core:)  I will also be updating the readmes, when I can, to reflect those who did some of the amazing coding changes!

**Comment by KMFDManic** [comment]
@frranck I am going to slowly but surely amend all of the readmes to reflectively give due credit to many of the libretro people who have worked on the commits for the various Cores.  Your name will be in the MrBoom ReadMe. Thanks so much for the awesome Bomber....err Dynablaster Experience!  Been a fan ever since Turbografx-16!

**Pull request merged**
